version: 2 
sources: 
  - name: jaffle_shop 
    description: This is a replica of the postgres databased used by our app 
    database: raw 
    schema : jaffle_shop 
    tables : 
      - name: customers 
        description:  one record per customer. 
      - name : orders 
        description:  one record per order. Includes cancelled and deleted orders. 
    